### ISSUE TITLE
include must be the last line in php-fpm.conf

### ISSUE THREAD

**Issue by infernix** [NBZ4live/ansible-php-fpm#5] opened 2014-04-03 13:32 UTC
If it isn't, everything after it will be parsed as part of what is above it.

That's bad design in php-fpm, but in the meantime this breaks the php-fpm.conf check every time something is added to it that wasn't present before the include.

Here's an ugly but working workaround:
```yml
- name: Copy the FPM configuration file
  ini_file: dest={{ php_fpm_conf }} section="{{ item.section }}" option="{{ item.option }}" value="{{ item.value }}" backup=yes
  with_items: fpm_config
  tags: [configuration,php,fpm]

- name: Delete the include line from the ini file
  ini_file: dest={{ php_fpm_conf }} section=global option=include backup=no state=absent
  with_items: fpm_config
  tags: [configuration,php,fpm]

- name: Readd the include line from the ini file
  ini_file: dest={{ php_fpm_conf }} section=global option=include backup=no state=present value="/etc/php5/fpm/pool.d/*"
  with_items: fpm_config
  notify: 
   - restart php-fpm
  tags: [configuration,php,fpm]
```

**Comment by lynxis** [comment] 2015-01-20 15:39
+1. I ran into this bug. It could be also fixed with lineinfile...

**Comment by NBZ4live** [comment] 2015-01-20 22:17
What OS do you run? And what configs did you use?
Can't reproduce it on Ubuntu

**Comment by infernix** [comment] 2015-01-21 00:11
This was on Debian 7. When there's content in fpm config *after* the "include=/etc/php5/fpm/pool.d/*" line, it doesn't get parsed as generic config but as part of the last pool config that's included.

**Closed** 2015-05-15 21:26 UTC
